---

collections:
  - name: community.general

roles:
  - name: lxc-sandbox
    src: https://github.com/gpenaud/ansible-role-lxc-sandbox
    version: master

  - name: rabbitmq
    src: https://github.com/stone-payments/ansible-rabbitmq
    version: master

  - name: geerlingguy.mysql

  - name: needys-api-need
    src: https://github.com/gpenaud/ansible-role-needys-api-need
    version: master

  - name: needys-output-producer
    src: https://github.com/gpenaud/ansible-role-needys-output-producer
    version: master
