
# ------------------------------------------------------------------------
# included vaulted variables (become password)
# ------------------------------------------------------------------------


# ------------------------------------------------------------------------
# create a lxc infrastructure to deploy needys apis, sidecar services, and
# supervision / logging tools
# ------------------------------------------------------------------------
- name: generate lxc infrastructure
  hosts: needys
  gather_facts: no
  roles:
  - role: lxc-infrastructure
    when: create_infrastructure is defined and create_infrastructure == "yes"
    tags: [always]

# ------------------------------------------------------------------------
# install envoy reverse-proxy
# ------------------------------------------------------------------------
- name: install envoy reverse-proxy
  hosts: needys-services
  gather_facts: yes
  roles:
  - role: envoy
    tags: [envoy]

# ------------------------------------------------------------------------
# install some services required by needys apis and services
# - mysql
# - rabbitmq
# ------------------------------------------------------------------------
- name: install needys sidecar services
  hosts: needys-services
  gather_facts: yes
  roles:
  - role: rabbitmq
    tags: [services, rabbitmq]
  - role: geerlingguy.mysql
    tags: [services, mysql]
  pre_tasks:
  - name: install gnupg for rabbitmq role
    package:
      name: gnupg
    tags: [services, rabbitmq]
  post_tasks:
  - name: copy bootstrap.sql to remote host
    copy:
      src: files/mysql/bootstrap.sql
      dest: /tmp
    register: copied_bootstrap
  - name: inject mysql test data in mysql sidecar service
    mysql_db:
      name: needys
      state: import
      target: /tmp/bootstrap.sql
    when: copied_bootstrap.changed

# -----------------------------------------------------------
# install prometheus and basic node exporters
# -----------------------------------------------------------
- name: install prometheus on services nodes
  hosts: needys-services
  gather_facts: yes
  roles:
  - role: prometheus
    tags: [supervision, prometheus]

- name: install node exporters on each needys node
  hosts: needys
  gather_facts: yes
  roles:
  - role: prometheus-node-exporter
    tags: [supervision, prometheus-exporters, node-exporter]

# -----------------------------------------------------------
# install services node exporters
# -----------------------------------------------------------
- name: install prometheus rabbitmq / mysqld exporters on services nodes
  hosts: needys-services
  gather_facts: yes
  roles:
  - role: prometheus-rabbitmq-exporter
    tags: [supervision, prometheus-exporters, rabbitmq-exporter]
  - role: prometheus-mysqld-exporter
    tags: [supervision, prometheus-exporters, mysqld-exporter]

# -----------------------------------------------------------
# install grafana for monitoring purposes:
# -----------------------------------------------------------
- name: install grafana to monitor needys
  hosts: needys-services
  gather_facts: no
  roles:
  - role: grafana
    tags: [supervision, grafana]
  post_tasks:
  - include: includes/import_grafana_dashboard.yml
    loop: "{{ lookup('fileglob', 'files/grafana_dashboards/*', wantlist=True) }}"
    loop_control:
      loop_var: dashboard
  tags: [supervision, grafana, grafana-dashboards]

# -----------------------------------------------------------
# install micro-services components of needys application:
# - needys-api-need
# - needys-output-producer
# -----------------------------------------------------------
- name: install needys micro-services
  hosts: needys-application
  gather_facts: no
  roles:
  - role: needys-api-need
    tags: [needys, needys-api-need]
  - role: needys-output-producer
    tags: [needys, needys-output-producer]
